<?php

namespace vetrinaBundle\Repository;

/**
 * DemandeEchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeEchangeRepository extends \Doctrine\ORM\EntityRepository
{public function ByidClient($id)
{
    $qb= $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.client=:id')
                ->orderBy('u.id')
                ->setParameter('id',$id);
        return $qb->getQuery()->getResult();
}
 public function bydemandeEchange($vetement)
 {$qb= $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.vetement IN (:vetement) and u.etat= :etat')
                ->orderBy('u.id')
                ->setParameter('vetement',$vetement)
                ->setParameter('etat','attente');
        return $qb->getQuery()->getResult();
     
     
     
 }
 public function Byidvetement($id)
{
    $qb= $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.vetement in (:id)')
                ->orderBy('u.id')
                ->setParameter('id',$id);
        return $qb->getQuery()->getResult();
}
 public function byidLivraison($id)
{$qb= $this->createQueryBuilder('u')
                ->select('u.Livraison')
                ->where('u.id=:id')
                ->orderBy('u.id')
                ->setParameter('id',$id);
        return $qb->getQuery()->getResult();
    
}
public function byLivraison($id)
{$qb= $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.Livraison IN (:id)')
               
                ->setParameter('id',$id);
        return $qb->getQuery()->getResult();
    
}
}
