services:
   tva :
      class: vetrinaBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }


   redirectionListener:
      class: vetrinaBundle\Listener\RedirectionListener
      arguments: [@service_container,@session]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }